[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "selenium>=4.29.0",
    "webdriver-manager>=4.0.2",
]
